# Generated by Django 4.1 on 2022-08-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=150)),
                ('grade', models.IntegerField(default=6)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
