# Generated by Django 4.1 on 2022-08-23 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='delievery_date',
            new_name='delivery_date',
        ),
        migrations.AlterModelTable(
            name='delivery',
            table='deliveries',
        ),
    ]
